-- MySQL Script generated by MySQL Workbench
-- Sat May 11 13:34:53 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema EniCa
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `EniCa` ;

-- -----------------------------------------------------
-- Schema EniCa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `EniCa` DEFAULT CHARACTER SET utf8 ;
USE `EniCa` ;

-- -----------------------------------------------------
-- Table `EniCa`.`zähler`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EniCa`.`zähler` (
  `zählernummer` INT NOT NULL,
  `zählerArt` ENUM('Strom', 'Gas', 'Wasser') NOT NULL,
  PRIMARY KEY (`zählernummer`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EniCa`.`tarif`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EniCa`.`tarif` (
  `idtarif` INT NOT NULL,
  `tarif_name` VARCHAR(45) NOT NULL,
  `preiskwh_in_cent` DECIMAL(6,2) NOT NULL,
  `grundgebuehr_in_cent` DECIMAL(6,2) NOT NULL,
  `tarif_beginn` DATE NULL,
  `tarif_ende` DATE NULL,
  `zählernummer` INT NULL,
  PRIMARY KEY (`idtarif`),
  INDEX `tarif_zählernummer_idx` (`zählernummer` ASC) VISIBLE,
  CONSTRAINT `tarif_zählernummer`
    FOREIGN KEY (`zählernummer`)
    REFERENCES `EniCa`.`zähler` (`zählernummer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EniCa`.`Ablesungen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EniCa`.`Ablesungen` (
  `idAblesungen` INT NOT NULL,
  `ablese_datum` DATE NOT NULL,
  `zählerstand` DECIMAL(10,2) NOT NULL,
  `zählernummer` INT NULL,
  PRIMARY KEY (`idAblesungen`),
  INDEX `ablesungen_zählernummer_idx` (`zählernummer` ASC) VISIBLE,
  CONSTRAINT `ablesungen_zählernummer`
    FOREIGN KEY (`zählernummer`)
    REFERENCES `EniCa`.`zähler` (`zählernummer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
